- composer.json
Replaced localgov_theme with localgov_theme_croydon.  Also mentioned localgov_theme as a directory dependency.
> Fixed theme names

- templates/system/footer.html.twig
The footer template file fell behind the new footer region declarations.
Previously we had only a *footer* region.  Now we have a footer_first
and a footer_second region.
> Footer region fix

- templates/localgov-alert-banner--full.html.twig
These comments are showing up as part of the [alert banner content](https://lbc-app-w-localgov-corpwebsite-p.azurewebsites.net/).  So I have just removed these comments.
> Removing code comments added by mistake

- localgov_theme_croydon.libraries.yml
The custom fonts for the theme were not rendering and this was eventually identified as an aggregation issue - this change disables aggregation on the font-face.css file.
> disable font aggregation to fix font issue on azure

- localgov_theme_croydon.theme
The Guides overview, Guides pages, and Service pages content types should occupy
two-thirds of the page width in wider displays.
> Empty sidebar for Guides and Service page

- assets/scss/lib/partials/_contact.scss
- gulpfile.js
- templates/field/address_plain.html.twig
- templates/field/field--paragraph--localgov-contact-heading--localgov-contact.html.twig
- templates/field/field--paragraph--localgov-contact-subheading--localgov-contact.html.twig
Updated the field names to match what the *LocalGov Contact* paragraph currently uses.
Also, added field templates for Plain Address, Contact heading, and Contact
subheading to match the UX.  These templates have been copied from the existing
"croydon" theme.
> Contact paragraph: Updated field names used in style rules

- localgov_theme_croydon.theme
Guides and Services pages should occupy two-thirds of the page width whether or nor there is a sidebar.  We are achieving this by telling these pages that a right sidebar is always present,
Previously, it was only doing so correctly when a right sidebar was absent.
> Bug fix for Guide and Service page content width

- templates/paragraph/paragraph--localgov-newsroom-teaser.html.twig
The News date should appear as the first item of the newsroom teaser.
> Newroom teaser: Added a News date field.

- localgov_theme_croydon.info.yml
- templates/system/header.html.twig
Added a new theme region for the Toggle menu.  This region can have its own menu
block which saves us from displaying the same menu block twice in one page.
Duplicate blocks lead to duplicate Ids in the markup which is invalid.
> A new theme region for the Toggle menu

- templates/field/field--node--localgov-directory-files--localgov-directories-venue.html.twig
- templates/field/file-link.html.twig
- templates/paragraph/paragraph--localgov-documents--default.html.twig
This is a change to the layout for the directory file downloads list. It now uses an h3 header, bullet list for the items and a 'small' tag for the file type and size. Also the downloads list appears in a table format on subsites pages - this has also been amended to reflect the correct format.
> fix directories downloads layout

- templates/localgov-alert-banner--full.html.twig
@Adnan-cds noticed that the 'remove the hide link' option for banners wasn't working and it was identified that the if statement controlling it had disappeared from the croydon version of the template. I have reinstated this and tested - all works ok.
> reinstate remove the hide link functionality

- templates/block/block--views-block--service-status-service-status-block.html.twig
The service status area looked visually different when used as an independent block at the bottom of a page rather than on the dedicated 'service-status'. To resolve, I created a service status block template and added the class it requires 'block-system-main-block'.
> modified block template for service status

- templates/system/header.html.twig
Removed the A to Z link from the header nav as it is no longer required.
> remove a to z link from the nav

- localgov_theme_croydon.theme
File types are displayed next to filenames (e.g. "foo.pdf (PDF, 123KB)") when Media Documents are rendered.  This wasn't working for several MSOffice file types.  Fixed now.
Fixed mime types:
- vnd.openxmlformats-officedocument.wordprocessingml.document -> Docx.
- vnd.openxmlformats-officedocument.spreadsheetml.sheet -> Spreadsheet.
- vnd.openxmlformats-officedocument.presentationml.presentation -> Powerpoint.
@see https://filext.com/faq/office_mime_types.html
> Fix for file types

- localgov_theme_croydon.theme
- templates/field/file-link.html.twig
File type value equates the file extension rather than the mimetype.
File metadata appears as part of the file link's anchor tag.
> Fix for file types: Use extension as file type.

- localgov_theme_croydon.theme
Adding a check for the presence of a background image before trying to use it.
> Hotfix: Call out box without background image

- templates/system/page.html.twig
Ticket info: Rollback page.html.twig when localgov theme next has a release (dec 2020)
I made a temporary change to 'page.html.twig' in the croydon theme. The long term fix has gone into the same file in localgov-theme. Once this is tagged for release and the croydon site is pulling in the the new changes from localgov-theme - then the 'content' block in this file should be removed.
Update: I have checked and the modified 'content' block is showing in the local gov theme version of this file so it is no longer required in the croydon duplicate,
> remove content block as per ticket instructions

- templates/eu-cookie-compliance-popup-info--cookie-settings-block.html.twig
- templates/eu-cookie-compliance-popup-info--override.html.twig
The fixed issue affects both Drupal 8 and Drupal 9.  Interestingly, Twig 1.x bundled with Drupal 8 never complained about it.  But Twig 2.x bundled with Drupal 9 is complaining.  Hence the fix.  This applies to both Drupal 8 and Drupal 9.  So safe for immediate deployment to the Drupal 8 site and later to the Drupal 9 site.
@see https://twig.symfony.com/doc/1.x/filters/replace.html
@see https://twig.symfony.com/doc/2.x/filters/replace.html
> Twig syntax fix.

- templates/system/header.html.twig
The logo URL was repeating the hostname due to a recent change in how resource URLs are generated in the ModernGov template page.  So instead of saying "https://example.net/logo/foo.png", it was generating "https://example.nethttps://example.net/logo.foo.png".  Fixed now and deployed to dev2.
> ModernGov template page: Fix for broken logo URL

- templates/system/footer.html.twig
- templates/system/header.html.twig
Replaced https://my.croydon.gov.uk with /myaccountheader which redirects to https://my.croydon.gov.uk/ at the moment but may change later.
> Updating URL of the "My account" page
